-- DB ADMINISTRATOR USER
CREATE USER "C##MEDTECHDBA" IDENTIFIED BY "medtechdba"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "C##MEDTECHDBA" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "C##MEDTECHDBA" ;

-- SYSTEM PRIVILEGES
GRANT DROP ANY TRIGGER TO "C##MEDTECHDBA" ;
GRANT ALTER ANY INDEX TO "C##MEDTECHDBA" ;
GRANT DROP ANY SEQUENCE TO "C##MEDTECHDBA" ;
GRANT CREATE TRIGGER TO "C##MEDTECHDBA" ;
GRANT ALTER ANY PROCEDURE TO "C##MEDTECHDBA" ;
GRANT CREATE ANY PROCEDURE TO "C##MEDTECHDBA" ;
GRANT CREATE ANY INDEX TO "C##MEDTECHDBA" ;
GRANT CREATE OPERATOR TO "C##MEDTECHDBA" ;
GRANT CREATE ANY SEQUENCE TO "C##MEDTECHDBA" ;
GRANT CREATE VIEW TO "C##MEDTECHDBA" ;
GRANT ALTER ANY TABLE TO "C##MEDTECHDBA" ;
GRANT SELECT ANY TABLE TO "C##MEDTECHDBA" ;
GRANT ALTER ANY SEQUENCE TO "C##MEDTECHDBA" ;
GRANT CREATE TABLE TO "C##MEDTECHDBA" ;
GRANT DROP ANY TABLE TO "C##MEDTECHDBA" ;
GRANT DROP ANY OPERATOR TO "C##MEDTECHDBA" ;
GRANT CREATE ANY OPERATOR TO "C##MEDTECHDBA" ;
GRANT CREATE TYPE TO "C##MEDTECHDBA" ;
GRANT CREATE TABLESPACE TO "C##MEDTECHDBA" ;
GRANT DROP ANY TYPE TO "C##MEDTECHDBA" ;
GRANT CREATE ANY SYNONYM TO "C##MEDTECHDBA" ;
GRANT DROP ANY SYNONYM TO "C##MEDTECHDBA" ;
GRANT EXECUTE ANY PROCEDURE TO "C##MEDTECHDBA" ;
GRANT CREATE SYNONYM TO "C##MEDTECHDBA" ;
GRANT CREATE SEQUENCE TO "C##MEDTECHDBA" ;
GRANT DROP ANY INDEX TO "C##MEDTECHDBA" ;
GRANT EXECUTE ANY OPERATOR TO "C##MEDTECHDBA" ;
GRANT UPDATE ANY TABLE TO "C##MEDTECHDBA" ;
GRANT DROP ANY VIEW TO "C##MEDTECHDBA" ;
GRANT ALTER ANY TRIGGER TO "C##MEDTECHDBA" ;
GRANT CREATE ANY VIEW TO "C##MEDTECHDBA" ;
GRANT READ ANY TABLE TO "C##MEDTECHDBA" ;
GRANT INSERT ANY TABLE TO "C##MEDTECHDBA" ;
GRANT ALTER ANY TYPE TO "C##MEDTECHDBA" ;
GRANT DROP ANY PROCEDURE TO "C##MEDTECHDBA" ;
GRANT CREATE ANY TRIGGER TO "C##MEDTECHDBA" ;
GRANT CREATE ANY TABLE TO "C##MEDTECHDBA" ;
GRANT CREATE ANY TYPE TO "C##MEDTECHDBA" ;
GRANT CREATE PROCEDURE TO "C##MEDTECHDBA" ;
GRANT ALTER ANY OPERATOR TO "C##MEDTECHDBA" ;

-- -- LOGISTIC TEAM USER
-- CREATE USER "C##LOGISTICTEAM_USER" IDENTIFIED BY "logisticteam"
-- DEFAULT TABLESPACE "USERS"
-- TEMPORARY TABLESPACE "TEMP";

-- -- QUOTAS
-- ALTER USER "C##LOGISTICTEAM_USER" QUOTA UNLIMITED ON "USERS";

-- -- ROLES
-- GRANT "CONNECT" TO "C##LOGISTICTEAM_USER" ;

-- -- OBJECT PRIVILEGES
-- -- Grant SELECT, INSERT, UPDATE, DELETE on specific tables.
-- -- A logistic team would likely view orders, update their status,
-- -- and perhaps view product batches.
-- GRANT SELECT, UPDATE ON "C##MEDTECHDBA".BatchOrder TO "C##LOGISTICTEAM_USER" ;
-- GRANT SELECT ON "C##MEDTECHDBA".ProductBatch TO "C##LOGISTICTEAM_USER" ;
-- GRANT SELECT ON "C##MEDTECHDBA".Product TO "C##LOGISTICTEAM_USER" ;
-- GRANT SELECT ON "C##MEDTECHDBA".Customer TO "C##LOGISTICTEAM_USER" ;
-- GRANT SELECT ON "C##MEDTECHDBA".LogisticTeam TO "C##LOGISTICTEAM_USER" ;
-- GRANT SELECT ON "C##MEDTECHDBA".ChiefOfficier TO "C##LOGISTICTEAM_USER" ;
-- GRANT SELECT ON "C##MEDTECHDBA".TeamMember TO "C##LOGISTICTEAM_USER" ;
-- GRANT SELECT ON "C##MEDTECHDBA".Department TO "C##LOGISTICTEAM_USER" ;
-- GRANT SELECT ON "C##MEDTECHDBA".DistributionCenter TO "C##LOGISTICTEAM_USER" ;
-- GRANT SELECT ON "C##MEDTECHDBA".Complaint TO "C##LOGISTICTEAM_USER" ;


-- -- Grant EXECUTE on necessary object types for DEREF and object creation/manipulation
-- GRANT EXECUTE ON "C##MEDTECHDBA".Location TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##MEDTECHDBA".ContactInfo TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##MEDTECHDBA".PhoneList TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##MEDTECHDBA".Product_t TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##MEDTECHDBA".ProdBatch_t TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##MEDTECHDBA".Customer_t TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##MEDTECHDBA".Department_t TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##MEDTECHDBA".DepartmentList TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##MEDTECHDBA".TeamMember_t TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##MEDTECHDBA".ChiefOfficier_t TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##MEDTECHDBA".MemberList TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##MEDTECHDBA".LogisticTeam_t TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##MEDTECHDBA".DistCenter_t TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##MEDTECHDBA".ProductList TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##MEDTECHDBA".BatchOrder_t TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##MEDTECHDBA".BatchList TO "C##LOGISTICTEAM_USER" ;
-- GRANT EXECUTE ON "C##MEDTECHDBA".PreferencesList TO "C##LOGISTICTEAM_USER" ;

COMMIT;